import XCTest

final class LiveCueUITests: XCTestCase {
    func testAssistantSelectionAndTiming() {
        let app = XCUIApplication(); app.launchArguments = ["-ui-testing"]; app.launch()
        app.buttons["start-session"].tap()
        app.buttons["assistant-lab"].tap()
        XCTAssertTrue(app.buttons["choose-gpt-6-astra"].waitForExistence(timeout: 5))
        XCTAssertTrue(app.buttons["choose-gpt-5.6-luna"].waitForExistence(timeout: 5))
        app.buttons["choose-gpt-5.6-luna"].tap()
        XCTAssertEqual(app.staticTexts["selected-assistant-model"].label, "gpt-5.6-luna")
        app.buttons["reasoning-picker"].tap()
        XCTAssertTrue(app.buttons["effort-none"].waitForExistence(timeout: 5))
        app.buttons["effort-none"].tap()
        XCTAssertTrue(app.staticTexts["Reasoning: none"].waitForExistence(timeout: 5))
        let selection = XCTAttachment(screenshot: app.screenshot()); selection.name = "Assistant model selection"; selection.lifetime = .keepAlways; add(selection)
        app.navigationBars.buttons.element(boundBy: 0).tap()
        app.buttons["assist-button"].tap()
        XCTAssertTrue(app.staticTexts["assistant-answer"].waitForExistence(timeout: 10))
        app.swipeUp()
        app.buttons["timing-disclosure"].tap()
        app.swipeUp()
        // LabeledContent exposes its label and value together to accessibility.
        XCTAssertTrue(app.staticTexts.matching(NSPredicate(format: "label BEGINSWITH %@", "PC: Codex CLI call,")).firstMatch.waitForExistence(timeout: 5))
        let timing = XCTAttachment(screenshot: app.screenshot()); timing.name = "Response timing breakdown"; timing.lifetime = .keepAlways; add(timing)
        app.swipeUp()
        XCTAssertTrue(app.buttons["retry-same-text"].exists)
        app.buttons["retry-same-text"].tap()
        XCTAssertTrue(app.staticTexts.matching(NSPredicate(format: "label BEGINSWITH %@", "Transcription (reused),")).firstMatch.waitForExistence(timeout: 5))
        let retry = XCTAttachment(screenshot: app.screenshot()); retry.name = "Same-text retry timing"; retry.lifetime = .keepAlways; add(retry)
    }
    func testConversationAndAssistFlow() {
        let app = XCUIApplication()
        app.launchArguments = ["-ui-testing"]
        app.launch()
        XCTAssertTrue(app.buttons["start-session"].waitForExistence(timeout: 10))
        app.buttons["start-session"].tap()
        XCTAssertTrue(app.staticTexts["What is the main advantage of local transcription?"].waitForExistence(timeout: 5))
        app.buttons["assist-button"].tap()
        XCTAssertTrue(app.staticTexts["assistant-answer"].waitForExistence(timeout: 10))
        let voz = XCTAttachment(screenshot: app.screenshot())
        voz.name = "Voz on Assist"; voz.lifetime = .keepAlways; add(voz)
        app.buttons["end-session"].tap()
        XCTAssertTrue(app.buttons["start-session"].waitForExistence(timeout: 5))
        app.tabBars.buttons["History"].tap()
        XCTAssertTrue(app.staticTexts.containing(NSPredicate(format: "label CONTAINS %@", "transcript segments")).firstMatch.waitForExistence(timeout: 5))
        app.tabBars.buttons["Settings"].tap()
        app.buttons["speech-provider"].tap()
        XCTAssertTrue(app.buttons["provider-parakeet"].waitForExistence(timeout: 5))
        app.buttons["provider-parakeet"].tap()
        app.tabBars.buttons["Live"].tap()
        app.buttons["download-model"].tap()
        app.buttons["Download & use"].tap()
        XCTAssertTrue(app.progressIndicators["model-download-progress"].waitForExistence(timeout: 5))
        XCTAssertTrue(app.buttons["Reload"].waitForExistence(timeout: 8))
        let download = XCTAttachment(screenshot: app.screenshot())
        download.name = "Download progress"; download.lifetime = .keepAlways; add(download)
        app.navigationBars.buttons.element(boundBy: 0).tap()
        XCTAssertTrue(app.buttons["start-session"].waitForExistence(timeout: 5))
        app.buttons["start-session"].tap()
        app.buttons["assist-button"].tap()
        XCTAssertTrue(app.staticTexts["assistant-answer"].waitForExistence(timeout: 10))
        let live = XCTAttachment(screenshot: app.screenshot())
        live.name = "Live Parakeet"; live.lifetime = .keepAlways; add(live)
    }

    func testPairingOffersQRScanner() {
        let app = XCUIApplication(); app.launchArguments = ["-ui-testing"]; app.launch()
        app.buttons["pair-pc"].tap()
        XCTAssertTrue(app.buttons["scan-pairing-qr"].waitForExistence(timeout: 5))
        let shot = XCTAttachment(screenshot: app.screenshot())
        shot.name = "QR pairing"; shot.lifetime = .keepAlways; add(shot)
    }
    func testMintSettingsAndCloudDisclosure() {
        let app = XCUIApplication(); app.launchArguments = ["-ui-testing"]; app.launch()
        app.tabBars.buttons["Settings"].tap()
        XCTAssertTrue(app.staticTexts["Midnight Mint"].exists || app.staticTexts.matching(NSPredicate(format: "label CONTAINS %@", "Midnight Mint")).firstMatch.exists)
        XCTAssertTrue(app.staticTexts.matching(NSPredicate(format: "label CONTAINS %@", "Audio streams through your PC to Meta")).firstMatch.exists)
        let shot = XCTAttachment(screenshot: app.screenshot()); shot.name = "Midnight Mint Settings"; shot.lifetime = .keepAlways; add(shot)
    }
}
